version: '3'
services:
  app:
    build: ./docker
    ports:
      - 100:80
      - 444:443
      - 5173:5173
      # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
  db:
    # platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpw

    # 追加
    volumes:
      - db-volume:/var/lib/mysql

# 追加
volumes:
  db-volume: